# Generated by Django 5.2.5 on 2025-08-23 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingjob',
            name='traceback',
        ),
        migrations.AddField(
            model_name='trainingjob',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='trainingjob',
            name='celery_task_id',
            field=models.CharField(blank=True, help_text='Celery task ID for this training job', max_length=255),
        ),
        migrations.AlterField(
            model_name='trainingjob',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='When the training job completed', null=True),
        ),
        migrations.AlterField(
            model_name='trainingjob',
            name='model',
            field=models.OneToOneField(help_text='The model being trained', on_delete=django.db.models.deletion.CASCADE, related_name='training_job', to='classification.mlmodel'),
        ),
        migrations.AlterField(
            model_name='trainingjob',
            name='progress_percentage',
            field=models.FloatField(default=0.0, help_text='Training progress as a percentage (0-100)'),
        ),
        migrations.AlterField(
            model_name='trainingjob',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text='When the training job started', null=True),
        ),
        migrations.AlterField(
            model_name='trainingjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the training job', max_length=20),
        ),
        migrations.AlterField(
            model_name='trainingjob',
            name='total_epochs',
            field=models.IntegerField(default=1, help_text='Total number of training epochs'),
        ),
    ]
