# Generated by Django 5.2.5 on 2025-08-24 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0002_remove_trainingjob_traceback_trainingjob_updated_at_and_more'),
        ('dataset_management', '0002_alter_datasetsample_dataset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingjob',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='trainingjob',
            name='traceback',
            field=models.TextField(blank=True, help_text='Full error traceback'),
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='dataset',
            field=models.ForeignKey(help_text='Dataset used for training', on_delete=django.db.models.deletion.CASCADE, related_name='models', to='dataset_management.dataset'),
        ),
        migrations.AlterField(
            model_name='modelcomparison',
            name='test_dataset',
            field=models.ForeignKey(blank=True, help_text='Dataset used for model comparison', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dataset_management.dataset'),
        ),
        migrations.AlterField(
            model_name='trainingjob',
            name='celery_task_id',
            field=models.CharField(help_text='Celery task ID for tracking', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='trainingjob',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainingjob',
            name='model',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='training_job', to='classification.mlmodel'),
        ),
        migrations.AlterField(
            model_name='trainingjob',
            name='progress_percentage',
            field=models.FloatField(default=0.0, help_text='Training progress (0-100%)'),
        ),
        migrations.AlterField(
            model_name='trainingjob',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainingjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='trainingjob',
            name='total_epochs',
            field=models.IntegerField(help_text='Total planned epochs'),
        ),
    ]
