# Generated by Django 5.2.5 on 2025-08-25 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0003_remove_trainingjob_updated_at_trainingjob_traceback_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlmodel',
            name='model_type',
            field=models.CharField(choices=[('bert', 'BERT-based (BioBERT/ClinicalBERT)'), ('gemma2-2b', 'Google Gemma 2B'), ('traditional', 'Traditional ML (SVM/Random Forest)'), ('hybrid', 'Hybrid Ensemble'), ('custom', 'Custom Architecture')], help_text='Type of ML model architecture', max_length=50),
        ),
    ]
