# Generated by Django 5.2.5 on 2025-08-25 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classification", "0004_alter_mlmodel_model_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="mlmodel",
            name="confusion_matrix",
            field=models.JSONField(
                blank=True,
                help_text="Confusion matrix as 2D array for model evaluation visualization",
                null=True,
            ),
        ),
    ]
